#ifndef STAYNORMAL_CHARACTERSETTINGS_HPP
#define STAYNORMAL_CHARACTERSETTINGS_HPP

#ifdef CHARACTER_SETTINGS
#error more than one character settings file
#endif

#define CHARACTER_SETTINGS

#define CHARACTER_HEIGHT_STAYNORMAL_CHARACTERSETTINGSUNDEFS 112
#define CHARACTER_WIDTH_STAYNORMAL_CHARACTERSETTINGSUNDEFS 50

#define CAST_STAYNORMAL_CHARACTERSETTINGSUNDEFS(what) static_cast<std::size_t>(what)
#define TYPE_CHECK_STAYNORMAL_CHARACTERSETTINGSUNDEFS(obj, type) assert(((std::is_same_v<decltype(obj), type>)))

#define ANIMATIONS_START_STAYNORMAL_CHARACTERSETTINGSUNDEFS(what, name) what::Character_Files what::name{{std::pair
#define ANIMATIONS_END_STAYNORMAL_CHARACTERSETTINGSUNDEFS }}

#define ANIMATION_CTOR_STAYNORMAL_CHARACTERSETTINGSUNDEFS(skin, animation) \
Animation{                                                                  \
ANIMATIONS_NAME[CAST_STAYNORMAL_CHARACTERSETTINGSUNDEFS(skin)]               \
[CAST_STAYNORMAL_CHARACTERSETTINGSUNDEFS(animation)].first,                   \
CHARACTER_WIDTH_STAYNORMAL_CHARACTERSETTINGSUNDEFS,                            \
CHARACTER_HEIGHT_STAYNORMAL_CHARACTERSETTINGSUNDEFS,                            \
ANIMATIONS_NAME[CAST_STAYNORMAL_CHARACTERSETTINGSUNDEFS(skin)]                   \
[CAST_STAYNORMAL_CHARACTERSETTINGSUNDEFS(animation)].second}

#endif //STAYNORMAL_CHARACTERSETTINGS_HPP
